using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace Romin
{
    // =========================================================
    // PARSER
    // =========================================================
    // Converts the token stream produced by the Lexer into
    // bytecode instructions that can later be executed by the VM.
    //
    // The parser is responsible for:
    // - recognizing statements and expressions;
    // - validating the syntax;
    // - managing local function scopes;
    // - generating bytecode;
    // - resolving local/global variables;
    // - creating jump instructions for control flow;
    // - creating function and table objects.
    public class Parser
    {
        #region Constructor

        // Creates a parser for a complete token stream.
        public Parser(List<Token> tokens, VMHost host)
        {
            T = tokens;
            Host = host;
        }

        // Creates a parser that uses an existing module.
        // This is mainly used when parsing expressions dynamically,
        // for example inside interpolated strings.
        private Parser(List<Token> tokens, VMHost host, Module module)
        {
            T = tokens;
            Host = host;
            Module = module;
        }

        #endregion

        #region Members

        // =========================
        // MEMBERS
        // =========================

        // Complete list of tokens produced by the lexer.
        private readonly List<Token> T;

        // Current token index.
        private int i;

        // Current token.
        private Token C => T[i];

        // Bytecode generated for the current module.
        private List<Instruction> Code => Module.Code;

        // Stack of active function scopes.
        // Each function introduces a new local variable scope.
        private Stack<FunctionScope> scopes = new();

        // Host provides access to system functionality and types.
        private readonly VMHost Host;

        // Current module being compiled.
        private Module Module;

        #endregion

        #region Methods

        // =========================
        // ENTRY
        // =========================

        // Starts parsing the token stream.
        // Statements are processed until the EOF token is reached.
        public Module Parse(Module mod = null)
        {
            Module = mod ?? new Module();
            while (C.Type != TokenType.EOF)
            {
                SkipNewLines();
                if (C.Type == TokenType.EOF)
                    break;

                Statement();
                SkipNewLines();
            }
            return Module;
        }

        /// <summary>
        /// Parses a single expression and adds its bytecode
        /// to an existing module.
        /// </summary>
        /// <param name="expression">
        /// Source code containing the expression.
        /// </param>
        /// <param name="host">
        /// VM host used to resolve types and system functionality.
        /// </param>
        /// <param name="module">
        /// Existing module to which the generated bytecode is added.
        /// </param>
        /// <exception cref="Exception">
        /// Thrown when unexpected tokens remain after the expression.
        /// </exception>
        public static void ParseExpression(
            string expression,
            VMHost host,
            Module module)
        {
            // Tokenize the expression first.
            var lexer = new Lexer(expression);
            var tokens = lexer.Tokenize();

            // Create a parser using the existing module.
            var parser = new Parser(tokens, host, module);

            // Parse the expression.
            parser.Expression();

            // The complete expression must consume all tokens.
            if (parser.C.Type != TokenType.EOF)
                throw new Exception(
                    $"Unexpected token {parser.C.Type}");
        }

        // =========================
        // STATEMENTS
        // =========================

        // Parses a single statement.
        // The first token determines which type of statement
        // should be parsed.
        void Statement()
        {
            SkipNewLines();

            // if statement
            if (C.Type == TokenType.If)
            {
                ParseIf();
                return;
            }

            // for statement
            if (C.Type == TokenType.For)
            {
                ParseFor();
                return;
            }

            // while statement
            if (C.Type == TokenType.While)
            {
                ParseWhile();
                return;
            }

            // use statement
            if (C.Type == TokenType.Use)
            {
                ParseUse();
                return;
            }

            // function declaration
            if (C.Type == TokenType.Fn)
            {
                ParseFunction();
                return;
            }

            // return statement
            if (C.Type == TokenType.Return)
            {
                ParseReturn();
                return;
            }

            // try/catch statement
            if (C.Type == TokenType.Try)
            {
                ParseTry();
                return;
            }

            // If no special statement was found,
            // parse an assignment or expression.
            ParseAssignmentOrExpression();
        }

        // =========================
        // IF
        // =========================

        // Parses an if/else statement and generates
        // conditional and unconditional jump instructions.
        void ParseIf()
        {
            // Consume the 'if' keyword.
            Expect(TokenType.If);

            ParseIfBody();
        }

        void ParseIfBody()
        {
            // Parse the condition.
            Expression();

            // Jump to the next else-if / else / end block if condition is false.
            int jumpFalse = Emit(OpCode.JumpIfFalse, T[i - 1], -1);

            // Parse the if body.
            Expect(TokenType.NewLine);
            ParseBlock();

            // Jump over all remaining else-if / else blocks.
            int jumpEnd = Emit(OpCode.Jump, T[i - 1], -1);

            // False condition comes here.
            PatchJump(jumpFalse);

            // else if
            if (C.Type == TokenType.Else)
            {
                Expect(TokenType.Else);

                if (C.Type == TokenType.If)
                {
                    // Consume "if" from "else if".
                    Expect(TokenType.If);

                    // Parse the next condition.
                    ParseIfBody();
                }
                else
                {
                    // Regular else.
                    Expect(TokenType.NewLine);
                    ParseBlock();
                }
            }

            // Continue after the whole if/else-if/else chain.
            PatchJump(jumpEnd);
        }

        // =========================
        // FOR IN 
        // =========================

        // Parses a 'for ... in ...' loop.
        // The loop supports either one variable or two variables,
        // for example:
        //
        // for item in collection
        // for key, value in collection
        void ParseFor()
        {
            Expect(TokenType.For);

            // First loop variable.
            string first = Expect(TokenType.Identifier).Value;

            // Optional second loop variable.
            string? second = null;

            if (Match(TokenType.Comma))
                second = Expect(TokenType.Identifier).Value;

            // Consume the 'in' keyword.
            Expect(TokenType.In);

            // =========================
            // 1. Always only expression
            // =========================

            // Parse the collection/range expression.
            Expression();

            // =========================
            // 2. INIT enumerator
            // =========================

            // Initialize the iterator.
            // Argument 1 means one loop variable.
            // Argument 2 means key/value iteration.
            Emit(OpCode.ForIterInit,
                T[i - 1],
                second != null ? 2 : 1);

            // Save the beginning of the loop.
            int loopStart = Code.Count;

            // =========================
            // 3. NEXT
            // =========================

            // Move the iterator to the next item.
            Emit(OpCode.ForIterNext, T[i - 1]);

            // Leave the loop when there are no more items.
            int jumpFalse = Emit(OpCode.JumpIfFalse, T[i - 1], -1);

            // =========================
            // 4. ASSIGN
            // =========================

            // Assign key/index and value for two-variable iteration.
            if (second != null)
            {
                EmitStore(second, T[i - 1]); // key/index
                EmitStore(first, T[i - 1]);  // value                  
            }
            else
            {
                // Assign the current item to the single variable.
                EmitStore(first, T[i - 1]);   // item
            }

            // =========================
            // 5. BODY
            // =========================

            // Parse the loop body.
            ParseBlock();

            // Jump back to the beginning of the iteration.
            Emit(OpCode.Jump, T[i - 1], loopStart);

            // Patch the exit jump.
            PatchJump(jumpFalse);
        }

        // =========================
        // WHILE
        // =========================

        // Parses a while loop.
        void ParseWhile()
        {
            Expect(TokenType.While);

            // Save the position where the loop condition starts.
            int loopStart = Code.Count;

            // Parse the loop condition.
            Expression();

            // If the condition is false, leave the loop.
            int jumpFalse =
                Emit(OpCode.JumpIfFalse, T[i - 1], -1);

            // Parse the loop body.
            Expect(TokenType.NewLine);
            ParseBlock();

            // Jump back to the condition.
            Emit(OpCode.Jump, T[i - 1], loopStart);

            // Patch the exit destination.
            PatchJump(jumpFalse);
        }

        // =========================
        // USE 
        // =========================

        // Parses the 'use' statement and loads the requested assembly.
        void ParseUse()
        {
            Expect(TokenType.Use);

            string asm = Expect(TokenType.String).Value;
            Host.Sys.Use(asm);
        }

        // =========================
        // RETURN 
        // =========================

        // Parses a return statement.
        void ParseReturn()
        {
            Expect(TokenType.Return);

            // return no value
            // If there is no expression after 'return',
            // return the Null value.
            if (C.Type == TokenType.NewLine ||
                C.Type == TokenType.Dedent ||
                C.Type == TokenType.EOF)
            {
                Emit(OpCode.LoadConst, T[i - 1], value: Value.Null);
                Emit(OpCode.Return, T[i - 1]);
                return;
            }

            // return expression
            // Parse and return the expression result.
            Expression();

            Emit(OpCode.Return, T[i - 1]);
        }

        // =========================
        // TRY CATCH 
        // =========================

        // Parses a try/catch block.
        void ParseTry()
        {
            Expect(TokenType.Try);
            Expect(TokenType.NewLine);

            // Create TryBegin with a temporary catch address.
            // The real address is known only after the try block
            // has been parsed.
            int tryBegin = Emit(OpCode.TryBegin, T[i - 1], -1);

            // Parse the try block.
            ParseBlock();

            // Mark the end of the protected section.
            Emit(OpCode.TryEnd, T[i - 1]);

            // If no exception occurs, skip the catch block.
            int jumpAfterCatch = Emit(OpCode.Jump, T[i - 1], -1);

            // catch
            Expect(TokenType.Catch);

            // Name of the variable that receives the exception.
            string errorName =
                Expect(TokenType.Identifier).Value;

            Expect(TokenType.NewLine);

            // Save the beginning of the catch block.
            int catchStart = Code.Count;

            // Patch TryBegin with the actual catch address.
            var ins = Code[tryBegin];
            ins.Arg = catchStart;
            Code[tryBegin] = ins;

            // Store the thrown exception in the catch variable.
            EmitStore(errorName, T[i - 1]);

            // Parse the catch body.
            ParseBlock();

            // Patch the jump that skips the catch block
            // when no exception occurred.
            var j = Code[jumpAfterCatch];
            j.Arg = Code.Count;
            Code[jumpAfterCatch] = j;
        }

        // =========================
        // FUNCTION 
        // =========================

        // Parses a function declaration and creates
        // a ScriptFunction object containing its bytecode address.
        void ParseFunction()
        {
            // Create a new local scope for the function.
            scopes.Push(new FunctionScope());

            Expect(TokenType.Fn);

            // Function name.
            string name = Expect(TokenType.Identifier).Value;

            Expect(TokenType.LParen);

            // Function parameter list.
            List<string> parameters = new();

            if (C.Type != TokenType.RParen)
            {
                do
                {
                    parameters.Add(
                        Expect(TokenType.Identifier).Value);
                }
                while (Match(TokenType.Comma));
            }

            // Register parameters as local variables.
            foreach (var p in parameters)
            {
                Scope.Locals[p] = Scope.NextLocalIndex++;
            }

            Expect(TokenType.RParen);
            Expect(TokenType.NewLine);

            // =========================
            // placeholder (jump over body later)
            // =========================

            // The main execution flow must skip the function body.
            // The jump destination is patched after the body is parsed.
            int jumpOverBody = Emit(OpCode.Jump, T[i - 1], -1);

            // Save the first instruction of the function body.
            int funcStart = Code.Count;

            // =========================
            // FUNCTION BODY START
            // =========================

            // Parse all statements inside the function.
            ParseBlock();

            // Every function implicitly returns Null
            // when it reaches the end without an explicit return.
            Emit(OpCode.LoadConst, T[i - 1], value: Value.Null);
            Emit(OpCode.Return, T[i - 1]);

            int funcEnd = Code.Count;

            // Patch the initial jump so normal execution
            // skips the function body.
            PatchJump(jumpOverBody);

            // =========================
            // CREATE FUNCTION OBJECT
            // =========================

            // Create the runtime function object.
            var fn = new ScriptFunction(
                funcStart,
                parameters.Count
            );

            // Store the function in the corresponding variable.
            EmitStoreFunction(name, fn, T[i - 1]);

            // Leave the function scope.
            scopes.Pop();
        }

        // Parses either an assignment, increment,
        // member assignment, or ordinary expression.
        void ParseAssignmentOrExpression()
        {
            if (IsSimpleAssignment())
            {
                ParseAssignment();
                return;
            }

            if (IsIncrement())
            {
                ParseIncrement();
                return;
            }

            if (IsMemberAssignment())
            {
                ParseMemberAssignment();
                return;
            }

            // Ordinary expression statement.
            Expression();

            // Remove the expression result from the stack.
            Emit(OpCode.Pop, T[i - 1]);
        }

        // Checks whether the current statement looks like
        // an assignment to an object/table member.
        bool IsMemberAssignment()
        {
            int j = i;

            if (T[j].Type != TokenType.Identifier)
                return false;

            // Search for '=' before the end of the statement.
            while (j < T.Count)
            {
                if (T[j].Type == TokenType.Equals)
                    return true;

                if (T[j].Type == TokenType.NewLine ||
                    T[j].Type == TokenType.EOF)
                    return false;

                j++;
            }

            return false;
        }

        // Parses assignments such as:
        //
        // object.name = value
        // object["name"] = value
        void ParseMemberAssignment()
        {
            // Load the root object.
            string root = Expect(TokenType.Identifier).Value;

            // First try to resolve the root as a local variable.
            if (scopes.Count > 0 && Scope.Locals.TryGetValue(root, out int local))
            {
                Emit(OpCode.LoadLocal, T[i - 1], local);
            }
            // Otherwise try to resolve it as a global variable.
            else if (Module.Env.TryGetIndex(root, out int global))
            {
                Emit(OpCode.LoadGlobal, T[i - 1], global);
            }
            else
            {
                throw new Exception($"{root} not found");
            }

            // Process a chain of member/index accesses.
            while (true)
            {
                // Object member access: object.name
                if (Match(TokenType.Dot))
                {
                    string name =
                        Expect(TokenType.Identifier).Value;

                    // Push the member name onto the stack.
                    Emit(OpCode.LoadConst, T[i - 1], value: new Value(name));

                    // If '=' follows, this member is the assignment target.
                    if (C.Type == TokenType.Equals)
                        break;

                    // Otherwise read the member value.
                    Emit(OpCode.GetIndex, T[i - 1]);
                    continue;
                }

                // Index access: object[expression]
                if (Match(TokenType.LBracket))
                {
                    Expression();
                    Expect(TokenType.RBracket);

                    // If '=' follows, this index is the assignment target.
                    if (C.Type == TokenType.Equals)
                        break;

                    // Otherwise read the indexed value.
                    Emit(OpCode.GetIndex, T[i - 1]);
                    continue;
                }

                break;
            }

            // Assignment operator.
            Expect(TokenType.Equals);

            // Parse the value being assigned.
            Expression();

            // Store the value into the selected member/index.
            Emit(OpCode.SetIndex, T[i - 1]);
        }

        // Checks for a simple variable assignment:
        // identifier = expression
        bool IsSimpleAssignment()
        {
            return C.Type == TokenType.Identifier &&
                   T[i + 1].Type == TokenType.Equals;
        }

        // Parses a simple variable assignment.
        void ParseAssignment()
        {
            string name = Expect(TokenType.Identifier).Value;
            Expect(TokenType.Equals);

            // Generate code for the right-hand side.
            Expression();

            // Store the result in the variable.
            EmitStore(name, T[i - 1]);
        }

        // Checks for postfix increment/decrement:
        // variable++
        // variable--
        bool IsIncrement()
        {
            return C.Type == TokenType.Identifier &&
                   (
                       T[i + 1].Type == TokenType.PlusPlus ||
                       T[i + 1].Type == TokenType.MinusMinus
                   );
        }

        // Parses variable++ and variable--.
        void ParseIncrement()
        {
            string name =
                Expect(TokenType.Identifier).Value;

            bool inc = Match(TokenType.PlusPlus);

            if (!inc)
                Expect(TokenType.MinusMinus);

            // load variable
            // Resolve the variable as local or global.
            if (scopes.Count > 0 &&
                Scope.Locals.TryGetValue(name, out int local))
            {
                Emit(OpCode.LoadLocal, T[i - 1], local);
            }
            else
            {
                int global = Module.Env.GetOrAdd(name);
                Emit(OpCode.LoadGlobal, T[i - 1], global);
            }

            // Load constant 1.
            Emit(OpCode.LoadConst, T[i - 1], value: new Value(1));

            // Add or subtract one.
            Emit(inc ? OpCode.Add : OpCode.Sub, T[i - 1]);

            // Store the updated value.
            EmitStore(name, T[i - 1]);
        }

        // =========================
        // TABLE LITERAL
        // =========================

        // Parses a table literal.
        //
        // Example:
        // [1, 2, 3]
        // [name: "John", age: 20]
        void ParseTable()
        {
            Expect(TokenType.LBracket);

            // Create an empty table.
            Emit(OpCode.CreateTable, T[i - 1]);

            // Automatically generated numeric index.
            int index = 1;

            while (C.Type != TokenType.RBracket)
            {
                string key;

                // Named table entry: key: value
                if (C.Type == TokenType.Identifier &&
                    i + 1 < T.Count &&
                    T[i + 1].Type == TokenType.Colon)
                {
                    key = Expect(TokenType.Identifier).Value;
                    Expect(TokenType.Colon);

                    // Push the string key.
                    Emit(OpCode.LoadConst, T[i - 1], value: new Value(key));
                }
                else
                {
                    // Automatically assign a numeric index.
                    Emit(OpCode.LoadConst, T[i - 1], value: new Value(index++));
                }

                // Parse the value.
                Expression();

                // Store the key/value pair into the table.
                Emit(OpCode.SetIndexMute, T[i - 1]);

                SkipNewLines();

                // Optional comma between entries.
                if (C.Type == TokenType.Comma)
                    i++;
            }

            Expect(TokenType.RBracket);
        }

        // =========================
        // EXPRESSIONS
        // =========================

        // Entry point for expression parsing.
        void Expression()
        {
            ParseTernary();
        }

        // Parses the ternary conditional operator.
        //
        // condition ? value1 : value2
        void ParseTernary()
        {
            ParseCoalesce();

            // No '?' means this is not a ternary expression.
            if (!Match(TokenType.Question))
                return;

            // If condition is false, jump to the second expression.
            int jumpFalse =
                Emit(OpCode.JumpIfFalse, T[i - 1], -1);

            // First expression.
            Expression();

            // Skip the second expression after evaluating the first.
            int jumpEnd =
                Emit(OpCode.Jump, T[i - 1], -1);

            // Set false branch.
            PatchJump(jumpFalse);

            Expect(TokenType.Colon);

            // Second expression.
            Expression();

            // Set final destination.
            PatchJump(jumpEnd);
        }

        // Parses the null-coalescing operator:
        // left ?? right
        void ParseCoalesce()
        {
            ParseOr();

            while (Match(TokenType.Coalesce))
            {
                // Continue with the left value if it is not null.
                int jumpNotNull =
                    Emit(OpCode.JumpIfNotNull, T[i - 1], -1);

                // Remove null value from the stack.
                Emit(OpCode.Pop, T[i - 1]);

                // Evaluate the right side.
                ParseOr();

                // Patch the jump to the end of the expression.
                PatchJump(jumpNotNull);
            }
        }

        // Parses logical OR expressions.
        void ParseOr()
        {
            ParseAnd();

            while (C.Type == TokenType.OrOr ||
                   C.Type == TokenType.Or)
            {
                i++;

                // Short-circuit if the left side is already true.
                int jumpTrue =
                    Emit(OpCode.JumpIfTrue, T[i - 1], -1);

                // Remove the previous result.
                Emit(OpCode.Pop, T[i - 1]);

                // Evaluate the right side.
                ParseAnd();

                // Patch short-circuit destination.
                PatchJump(jumpTrue);
            }
        }

        // Parses logical AND expressions.
        void ParseAnd()
        {
            ParseEquality();

            while (C.Type == TokenType.AndAnd ||
                   C.Type == TokenType.And)
            {
                i++;

                // Short-circuit if the left side is false.
                int jumpFalse =
                    Emit(OpCode.JumpIfFalse, T[i - 1], -1);

                // Remove the previous result.
                Emit(OpCode.Pop, T[i - 1]);

                // Evaluate the right side.
                ParseEquality();

                // Patch short-circuit destination.
                PatchJump(jumpFalse);
            }
        }

        // Parses equality operators:
        // == and !=
        void ParseEquality()
        {
            ParseCompare();

            while (true)
            {
                TokenType op = C.Type;

                if (op != TokenType.EqualEqual &&
                    op != TokenType.NotEqual)
                    break;

                i++;

                // Parse the right operand.
                ParseCompare();

                // Generate the corresponding comparison instruction.
                EmitBinary(op);
            }
        }

        // Parses comparison operators:
        // >, <, >=, <=
        void ParseCompare()
        {
            ParseAdd();

            while (true)
            {
                TokenType op = C.Type;

                if (op != TokenType.Greater &&
                    op != TokenType.Less &&
                    op != TokenType.GreaterEqual &&
                    op != TokenType.LessEqual)
                    break;

                i++;

                // Parse the right operand.
                ParseAdd();

                // Generate the comparison instruction.
                EmitBinary(op);
            }
        }

        // Parses addition, subtraction and range expressions.
        void ParseAdd()
        {
            ParseMul();

            while (true)
            {
                TokenType op = C.Type;

                if (op != TokenType.Plus &&
                    op != TokenType.Minus &&
                    op != TokenType.DotDot)
                    break;

                i++;

                // Parse the right operand.
                ParseMul();

                // Generate the corresponding instruction.
                EmitBinary(op);
            }
        }

        // Parses multiplication and division.
        void ParseMul()
        {
            ParseUnary();

            while (true)
            {
                TokenType op = C.Type;

                if (op != TokenType.Star &&
                    op != TokenType.Slash)
                    break;

                i++;

                // Parse the right operand.
                ParseUnary();

                // Generate the arithmetic instruction.
                EmitBinary(op);
            }
        }

        // Parses unary operators:
        // !expression
        // -expression
        // +expression
        void ParseUnary()
        {
            // Logical NOT.
            if (Match(TokenType.Not))
            {
                ParseUnary();

                Emit(OpCode.Not, T[i - 1]);

                return;
            }

            // Unary minus.
            if (Match(TokenType.Minus))
            {
                ParseUnary();

                Emit(OpCode.Negate, T[i - 1]);

                return;
            }

            // Unary plus does not generate an instruction.
            if (Match(TokenType.Plus))
            {
                ParseUnary();
                return;
            }

            // Parse the basic value.
            ParsePrimary();

            // Parse postfix operations such as
            // function calls, member access and indexing.
            ParsePostfix();
        }

        // Parses the basic/primary expression.
        void ParsePrimary()
        {
            // (expr)
            // Parenthesized expression.
            if (Match(TokenType.LParen))
            {
                Expression();
                Expect(TokenType.RParen);
                return;
            }

            // table
            if (C.Type == TokenType.LBracket)
            {
                ParseTable();
                return;
            }

            // number
            if (C.Type == TokenType.Number)
            {
                string raw = Expect(TokenType.Number).Value;

                Value v;

                // Decimal literal.
                // Examples:
                // 123m
                // 123.45m
                // 123.45M
                if (raw.EndsWith("m", StringComparison.OrdinalIgnoreCase))
                {
                    string number = raw[..^1];

                    v = new Value(
                        decimal.Parse(
                            number,
                            CultureInfo.InvariantCulture));
                }
                // Floating-point literal.
                else if (raw.Contains("."))
                {
                    v = new Value(
                        double.Parse(
                            raw,
                            CultureInfo.InvariantCulture));
                }
                // Integer literal.
                else
                {
                    v = new Value(int.Parse(raw));
                }

                Emit(OpCode.LoadConst, T[i - 1], value: v);
                return;
            }

            // string
            if (C.Type == TokenType.String)
            {
                string v = Expect(TokenType.String).Value;

                Emit(OpCode.LoadConst, T[i - 1], value: new Value(v));

                return;
            }

            // $"..."
            // Interpolated string.
            if (C.Type == TokenType.InterpolatedString)
            {
                ParseInterpolatedString();
                return;
            }

            // bool
            // Boolean literal: true.
            if (Match(TokenType.True))
            {
                Emit(OpCode.LoadConst, T[i - 1], value: new Value(true));
                return;
            }

            // Boolean literal: false.
            if (Match(TokenType.False))
            {
                Emit(OpCode.LoadConst, T[i - 1], value: new Value(false));
                return;
            }

            // new Type()
            // Create a new object instance.
            if (Match(TokenType.New))
            {
                // Parse the fully qualified type name.
                string typeName = ParseTypeName();

                // Load the type object.
                Emit(OpCode.LoadType, T[i - 1], value: new Value(typeName));

                // Parse constructor arguments.
                ParseCallAfterNew();

                return;
            }

            // null
            if (Match(TokenType.Null))
            {
                Emit(OpCode.LoadConst, T[i - 1], value: Value.Null);
                return;
            }

            // identifier
            if (C.Type == TokenType.Identifier)
            {
                ParseIdentifier();
                return;
            }

            // Nothing matched, so the current token is invalid here.
            throw new Exception($"Unexpected token {C.Type}");
        }

        // Parses postfix operations following a primary expression.
        //
        // Examples:
        // function()
        // object.name
        // array[index]
        void ParsePostfix()
        {
            while (true)
            {
                // Function call.
                if (Match(TokenType.LParen))
                {
                    ParseCall();
                    continue;
                }

                // Member access.
                if (Match(TokenType.Dot))
                {
                    ParseDot();
                    continue;
                }

                // Index access.
                if (Match(TokenType.LBracket))
                {
                    ParseIndex();
                    continue;
                }

                break;
            }
        }

        // Resolves and loads an identifier.
        void ParseIdentifier()
        {
            string name = Expect(TokenType.Identifier).Value;

            // Built-in function.
            if (IsBuiltin(name))
            {
                ParseBuiltinCall(name);
                return;
            }

            // Local variable.
            if (scopes.Count > 0 && Scope.Locals.ContainsKey(name))
            {
                Emit(OpCode.LoadLocal, T[i - 1], Scope.Locals[name]);
                return;
            }

            // Global variable.
            if (Module.Env.TryGetIndex(name, out int global))
            {
                Emit(OpCode.LoadGlobal, T[i - 1], global);
                return;
            }

            // .NET type available through the host.
            if (Host.Sys.FindType(name) is Type t)
            {
                Emit(OpCode.LoadType, T[i - 1], value: new Value(t));
                return;
            }

            // Identifier could not be resolved.
            throw new Exception($"Unknown identifier: {name}");
        }

        // Parses an interpolated string.
        //
        // Example:
        // $"Hello {name}"
        //
        // The string is split into constant text and expressions.
        void ParseInterpolatedString()
        {
            Token token = Expect(TokenType.InterpolatedString);

            // Split the string into text/expression parts.
            var parts = SplitInterpolatedString(token.Value);

            // Empty string.
            if (parts.Count == 0)
            {
                Emit(OpCode.LoadConst, token, value: new Value(""));
                return;
            }

            bool first = true;

            foreach (var part in parts)
            {
                if (part.IsExpression)
                {
                    // Parse the expression contained inside { }.
                    ParseExpression(
                        part.Text,
                        Host,
                        Module);
                }
                else
                {
                    // Load literal text.
                    Emit(
                        OpCode.LoadConst,
                        token,
                        value: new Value(part.Text));
                }

                // Combine all parts using the Add operation.
                if (!first)
                    Emit(OpCode.Add, token);

                first = false;
            }
        }

        // Parses an indexed expression:
        // object[index]
        void ParseIndex()
        {
            // Parse the index expression.
            Expression();

            Expect(TokenType.RBracket);

            // Read the indexed value.
            Emit(OpCode.GetIndex, T[i - 1]);
        }

        // Parses member access:
        // object.property
        void ParseDot()
        {
            // Read the property name.
            string prop = Expect(TokenType.Identifier).Value;

            // Convert the property name into a Value.
            Emit(OpCode.LoadConst, T[i - 1], value: new Value(prop));

            // Read the property through the index operation.
            Emit(OpCode.GetIndex, T[i - 1]);
        }

        // Parses a normal function call.
        void ParseCall()
        {
            int argc = 0;

            // Parse all arguments.
            if (C.Type != TokenType.RParen)
            {
                do
                {
                    Expression();
                    argc++;
                }
                while (Match(TokenType.Comma));
            }

            Expect(TokenType.RParen);

            // Generate the function call instruction
            // with the number of arguments.
            Emit(OpCode.Call, T[i - 1], argc);
        }

        // Parses a built-in function call.
        void ParseBuiltinCall(string name)
        {
            // Put the built-in function name onto the stack.
            Emit(OpCode.LoadConst, T[i - 1], value: new Value(name));

            Expect(TokenType.LParen);

            int argc = 0;

            // Parse arguments.
            if (C.Type != TokenType.RParen)
            {
                do
                {
                    Expression();
                    argc++;
                }
                while (Match(TokenType.Comma));
            }

            Expect(TokenType.RParen);

            // Generate a dedicated built-in call instruction.
            Emit(OpCode.CallBuiltin, T[i - 1], argc);
        }

        // Parses constructor arguments after 'new Type'.
        void ParseCallAfterNew()
        {
            Expect(TokenType.LParen);

            int argc = 0;

            // Parse constructor arguments.
            if (C.Type != TokenType.RParen)
            {
                do
                {
                    Expression();
                    argc++;
                }
                while (Match(TokenType.Comma));
            }

            Expect(TokenType.RParen);

            // Generate object construction instruction.
            Emit(OpCode.New, T[i - 1], argc);
        }

        // Parses a possibly fully-qualified type name.
        //
        // Example:
        // System.Text.StringBuilder
        string ParseTypeName()
        {
            string name = Expect(TokenType.Identifier).Value;
            var sb = new StringBuilder(name);

            // Append all namespace/type segments.
            while (Match(TokenType.Dot))
            {
                sb.Append('.');
                sb.Append(Expect(TokenType.Identifier).Value);
            }

            return sb.ToString();
        }

        // =========================
        // BLOCK
        // =========================

        // Parses an indented block.
        //
        // The lexer produces Indent and Dedent tokens,
        // which allows the parser to treat indentation
        // as the block boundary.
        void ParseBlock()
        {
            SkipNewLines();

            // A block must begin with an indentation token.
            Expect(TokenType.Indent);

            while (C.Type != TokenType.Dedent &&
                   C.Type != TokenType.EOF)
            {
                Statement();
                SkipNewLines();
            }

            // Consume the end of the indentation block.
            Expect(TokenType.Dedent);
        }

        // =========================
        // HELPERS
        // =========================

        // Checks whether the current token matches the requested type.
        // If it matches, advances to the next token.
        bool Match(TokenType t)
        {
            if (C.Type == t)
            {
                i++;
                return true;
            }

            return false;
        }

        // Requires the current token to have the specified type.
        // Throws an exception if the token is unexpected.
        Token Expect(TokenType t)
        {
            if (C.Type != t)
                throw new Exception($"Expected {t}, got {C.Type}");

            return T[i++];
        }

        // Skips all consecutive newline tokens.
        void SkipNewLines()
        {
            while (C.Type == TokenType.NewLine)
                i++;
        }

        // Replaces a previously unknown jump destination
        // with the current end of the generated bytecode.
        void PatchJump(int index)
        {
            var ins = Code[index];
            ins.Arg = Code.Count;
            Code[index] = ins;
        }

        // Returns the currently active function scope.
        FunctionScope Scope => scopes.Peek();

        // =========================
        // Emits
        // =========================

        // Converts a parser-level binary operator into
        // the corresponding VM opcode.
        void EmitBinary(TokenType op)
        {
            switch (op)
            {
                case TokenType.Plus: Emit(OpCode.Add, T[i - 1]); break;
                case TokenType.Minus: Emit(OpCode.Sub, T[i - 1]); break;
                case TokenType.Star: Emit(OpCode.Mul, T[i - 1]); break;
                case TokenType.Slash: Emit(OpCode.Div, T[i - 1]); break;

                case TokenType.EqualEqual: Emit(OpCode.Equal, T[i - 1]); break;
                case TokenType.NotEqual: Emit(OpCode.NotEqual, T[i - 1]); break;

                case TokenType.Greater: Emit(OpCode.Greater, T[i - 1]); break;
                case TokenType.Less: Emit(OpCode.Less, T[i - 1]); break;

                case TokenType.GreaterEqual: Emit(OpCode.GreaterEqual, T[i - 1]); break;
                case TokenType.LessEqual: Emit(OpCode.LessEqual, T[i - 1]); break;

                case TokenType.AndAnd: Emit(OpCode.And, T[i - 1]); break;
                case TokenType.OrOr: Emit(OpCode.Or, T[i - 1]); break;

                // '..' creates a range.
                case TokenType.DotDot: Emit(OpCode.MakeRange, T[i - 1]); break;

                default:
                    // This should only be reached if a new operator
                    // is added to the lexer/parser but not handled here.
                    throw new Exception($"Unsupported op {op}");
            }
        }

        // Adds a new instruction to the current module's bytecode.
        //
        // The source location is copied from the token so that
        // runtime errors can later point back to the original source.
        int Emit(OpCode op, Token token, int arg = 0, Value value = default)
        {
            Code.Add(new Instruction
            {
                Op = op,
                Arg = arg,
                Value = value,

                // Preserve source location information.
                Line = token.Line,
                Column = token.Column,
                File = token.File
            });

            // Return the index of the newly generated instruction.
            return Code.Count - 1;
        }

        // Stores the value currently on the stack
        // into either a local or global variable.
        void EmitStore(string name, Token token)
        {
            // Store into a local variable when it exists
            // in the current function scope.
            if (scopes.Count > 0 && Scope.Locals.ContainsKey(name))
            {
                int index = Scope.Locals[name];

                Emit(OpCode.StoreLocal, T[i - 1], index);
            }
            else
            {
                // Otherwise store into the module's global environment.
                int index = Module.Env.GetOrAdd(name);

                Emit(OpCode.StoreGlobal, T[i - 1], index);
            }
        }

        // Creates a ScriptFunction object and stores it
        // in a variable.
        void EmitStoreFunction(string name, ScriptFunction fn, Token token)
        {
            // Create a runtime function object.
            Emit(OpCode.CreateFunction, token, value: new Value(fn));

            // Store the function object in its variable.
            EmitStore(name, T[i - 1]);
        }

        // Checks whether a name represents a built-in function.
        bool IsBuiltin(string name)
        {
            return name == "load"
                || name == "print";
        }

        // Splits an interpolated string into literal and expression parts.
        //
        // Example:
        // "Hello {name}, value = {x}"
        //
        // becomes:
        // Text       -> "Hello "
        // Expression -> "name"
        // Text       -> ", value = "
        // Expression -> "x"
        //
        // 'depth' allows nested braces to be tracked.
        List<InterpolatedPart> SplitInterpolatedString(string text)
        {
            var result = new List<InterpolatedPart>();
            var sb = new StringBuilder();
            int depth = 0;

            foreach (char c in text)
            {
                // Opening brace starts an expression
                // when we are not already inside one.
                if (c == '{')
                {
                    if (depth == 0)
                    {
                        // Save preceding literal text.
                        if (sb.Length > 0)
                        {
                            result.Add(new InterpolatedPart(false, sb.ToString()));
                            sb.Clear();
                        }
                    }
                    else
                    {
                        // Nested opening brace belongs to the expression.
                        sb.Append(c);
                    }

                    depth++;
                    continue;
                }

                // Closing brace ends the current expression.
                if (c == '}')
                {
                    depth--;

                    if (depth == 0)
                    {
                        // Save the completed expression.
                        result.Add(new InterpolatedPart(true, sb.ToString()));
                        sb.Clear();
                    }
                    else
                    {
                        // Nested closing brace belongs to the expression.
                        sb.Append(c);
                    }

                    continue;
                }

                // Ordinary character.
                sb.Append(c);
            }

            // Save remaining literal text.
            if (sb.Length > 0)
                result.Add(new InterpolatedPart(false, sb.ToString()));

            return result;
        }

        #endregion

        #region Classes

        // Stores information about local variables
        // belonging to one function.
        class FunctionScope
        {
            // Maps local variable names to VM local indexes.
            public Dictionary<string, int> Locals = new();

            // Index of the next available local variable slot.
            public int NextLocalIndex = 0;
        }

        // Represents one part of an interpolated string.
        //
        // IsExpression == false:
        //     literal text
        //
        // IsExpression == true:
        //     Romin expression that must be parsed and evaluated
        sealed class InterpolatedPart
        {
            public bool IsExpression;
            public string Text;

            public InterpolatedPart(bool isExpression, string text)
            {
                IsExpression = isExpression;
                Text = text;
            }

            // Useful for debugging and logging.
            public override string ToString()
            {
                return $"{(IsExpression ? "Expr" : "Text")} : {Text}";
            }
        }

        #endregion
    }
}
